GET http://localhost:3001/api/vacancy/getAllCavancies?page=1&salaryFrom=30000&salaryTo=50000&expFrom=0&expTo=6

###

GET http://localhost:3001/api/vacancy/getAllCavancies?search=python


###

GET http://45.80.68.253:3001/api/vacancy/getAllCavancies